### ISSUE TITLE
Client code called on server side

### ISSUE THREAD

**Issue by Darkosto** [abecderic/clay-bucket#1]
Hello!

I believe Clay Buckets may be calling client side code on the server and causing my server to crash during load. Upon removal, the server starts up just fine.

This is the crash associated with it, I know it doesn't label any mod specifically:
http://pastebin.com/xLqRm1N4

Thank you for looking into this :)
Darkosto

**Comment by abecderic** [comment]
You are correct, Clay Bucket was calling client side code on the server. Your crash log actually blames Clay Bucket: In line 96 the "E" means errored.
