### ISSUE TITLE
Clay bucket will not fill Petal Apothecary from Botania

### ISSUE THREAD

**Issue by lilmoefow** [abecderic/clay-bucket#3]
I can not use your clay bucket to fill the Petal Apothecary with water from Botania, this is in the 1.7.10 version.

Forge 1.7.10 1614
Botania r1.8-249
ClayBucket-1.7.10-1.1

**Comment by lilmoefow** [comment]
Thank you for the quick response

**Comment by abecderic** [comment]
Not a problem :) the file is now up on curse
